language: rust
rust:
        - stable
        - beta
        - nightly

matrix:
        allow_failures:
                - rust: nightly
        fast_finish: true

before_script:
        - rustup component add clippy rustfmt

script:
        - cargo build --features reqwest-09x
        - cargo test --features reqwest-09x
        - cargo clippy
        - cargo fmt -- --check
